# Generated by Django 4.2.3 on 2023-08-22 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blogpost_chead0_blogpost_chead1_blogpost_chead2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='chead2',
            field=models.CharField(default=0, max_length=5000),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='head2',
            field=models.CharField(default=0, max_length=5000),
        ),
    ]
